meteor:
  image: danieldent/meteor
  command: vboxsf-shim meteor
  links:
    - mongo:db
  volumes:
    - ./:/app
  ports:
    - 3000:3000
  cap_add:
    - SYS_ADMIN
  environment:
    MONGO_URL: mongodb://db

mongo:
  image: mongo
